name: github-actions-for-nest

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Build NestJS
      - run: npm run nest build

    runs:
      using: 'docker'
      image: 'Dockerfile'
